### ISSUE TITLE
γεια σου αδερφε

### ISSUE THREAD

**Issue by panaeolus** [acidvegas/spaggiari#1]
πως μπορω να ερθω σε επαφη?
θελω να δουλεψω το σκριπτακι σου
ευχαριστω

**Comment by acidvegas** [comment]
XMPP / IRC ο αδερφός μου

**Comment by hlolli** [comment]
@panaeolus Hope you can see this message. But this is the only thing that you've done on github.com, which is to create this issue.

The case is this, I have an application called panaeolus and because of your username choice I can't create an orgaization with that name. Only if you're not planing to use github.com, which seems to be the case, could you either delete your account or change the username. You are by no means forced to do that and you're compleatly allowed to keep it. I just thought I'd ask in the unlikely event you'd be ok with this.
